name: PHP CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install required libraries
      run: sudo apt-get update -yqq && sudo apt-get install php-pcov

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check coding style
      run: composer test:php-cs-fixer
